Remove TF files (for now) -> Move towards SAM for  80% of IaC management

diff --git a/.github/workflows/infra_deploy.yml b/.github/workflows/infra_deploy.yml
--- a/.github/workflows/infra_deploy.yml
+++ b/.github/workflows/infra_deploy.yml
@@ -7,33 +7,60 @@ on:
     paths: 
       - infrastructure/**
 jobs:
-  terraform:
-    name: "Terraform"
+  # TODO: bring back TF for very specific IaC, majority of AWS resources (Lambdas, etc.) to be 
+  #       populated by SAM
+  # terraform:
+  #   name: "Terraform"
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     AWS_ACCESS_KEY_ID: ${{ secrets.ADMIN_AWS_KEY_ID }}
+  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.ADMIN_AWS_SECRET_KEY }}
+  #     AWS_REGION: us-west-2
+
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+
+  #     - name: Terraform Init
+  #       id: init
+  #       run: cd infrastructure && terraform init
+
+  #     - name: Terraform Plan
+  #       id: plan
+  #       run: cd infrastructure && terraform plan 
+
+  #     - name: Terraform Plan Status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
+
+  #     - name: Terraform Apply
+  #       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+  #       run: cd infrastructure && terraform apply -auto-approve
+  aws-sam:
+    name: "AWS SAM Deploy"
     runs-on: ubuntu-latest
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.ADMIN_AWS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.ADMIN_AWS_SECRET_KEY }}
       AWS_REGION: us-west-2
-
+    defaults:
+      run:
+        working-directory: ./infrastructure/quadball-processing
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-
-      - name: Terraform Init
-        id: init
-        run: cd infrastructure && terraform init
-
-      - name: Terraform Plan
-        id: plan
-        run: cd infrastructure && terraform plan 
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: cd infrastructure && terraform apply -auto-approve
+      - name: Setup Sam
+        uses: aws-actions/setup-sam@v1
+      - name: Configure AWS CREDS
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.ADMIN_AWS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.ADMIN_AWS_SECRET_KEY }}
+          aws-region: us-west-2
+      - name: Build
+        run: sam build
+      - name: Deploy
+        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
